server:
  port: 8181
  
debug: false

logging.level:
  org.springframework.security: ERROR
  org.hibernate: INFO
  org.flywaydb: INFO
  
spring:
  datasource:
    url: jdbc:h2:file:${user.home}/simple_inventory_db_instance_h2/INVENTORY_DB;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: admin
    password: admin321
  jpa.hibernate:
    ddl-auto: none
  profiles:
   active: dev
   
flyway:
  locations: db/migration/h2

hibernate:
  show_sql: true
  format_sql: true
  
app:
  property:
    #tokenTTLSeconds: 30
    #surgePriceModelAccessTimeMins: 60
    #surgePriceModelViewsPerAccessTimeThreshold: 10
    #surgePriceModelPriceIncreasePercent: 0.10 
    
